### ISSUE TITLE
How to support reflect with a dict of table names and database views

### ISSUE THREAD

**Issue by gsvitak** [dgilland/alchy#32]
Hello

Thanks for the work. It makes integrating SqlAlchemy into a custom framework a snap.

I have an existing database with some database views. I want to reflect the database to map the tables and the views in a dictionary. 

1) How would I support only reflecting a select set of tables?
2) How would I support reflecting views? I noticed the reflect method only support tables in the metadata?

Would I follow the Flask pattern and subclass the Manager class and override the needed methods?

Thanks
Greg

**Comment by dgilland** [comment]
It looks like SQLAlchemy's [reflect()](http://docs.sqlalchemy.org/en/latest/core/metadata.html#sqlalchemy.schema.MetaData.reflect) method supports an `only` argument that can be used to limit the reflection to subset of table names. However, alchy doesn't expose that option in the `Manager.reflect()` method (but obviously you can subclass it to extend that behavior).

For view, SQLAlchemy has a way to reflect views: http://docs.sqlalchemy.org/en/latest/core/reflection.html#reflecting-views

**Comment by gsvitak** [comment]
Thanks for the info. Can you please provide an example of how to use the only parameter? 

I only have 1 database and when I pass a dictionary to the method of the table names, I get a message stating that the mapping is not available in SQLALCHEMY_BINDS object.

Thanks,
G

**Comment by dgilland** [comment]
What's your code that produces the error?

**Comment by gsvitak** [comment]
```
class Base(ModelBase):
    # extend/override ModelBase if necessary
    pass

Model = make_declarative_base(Base=Base)

config = {
    'SQLALCHEMY_DATABASE_URI': conn_string,
}

reflect_tables = ['general_correspondence']
db = Manager(config=config, Model=Model)
db.reflect(reflect_tables)
```

**Comment by dgilland** [comment]
`alchy.Manager.reflect` doesn't support the `only` argument. That's something that's supported in SQLAlchemy's reflect() method but alchy doesn't curry that argument to it unfortunately. So you would need to extend `Manager`:

- https://github.com/dgilland/alchy/blob/develop/alchy/manager.py#L279
- https://github.com/dgilland/alchy/blob/develop/alchy/manager.py#L249

**Comment by gsvitak** [comment]
Oh.. stupid on my part.. I misread your previous response. Thanks.

Greg
